version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "github"
            - "Docker Hub"

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: |
            make shellcheck

      - run:
          name: Create SD image
          command: |
            VERSION=${CIRCLE_TAG} make sd-image

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp hypriotos*zip* output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              go install github.com/tcnksm/ghr@latest
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ghr $pre -u $GITHUB_USER $CIRCLE_TAG output/
            fi
